# Site wide configuration

title: Thomas Reynaud
description: A French data scientist in NY
logo: avatar.png
teaser: teaser.png
locale: en
# url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Thms
  email: thmsreynaud@gmail.com
  twitter: Thmsrey
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: avatar.png
  disqus-shortname: thmsreynaud


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
